/**
 * Feature parity with the inbox at 5c99fe6 (main before the phone redesign).
 * A later layout pass must keep these controls and API triggers.
 */
const fs = require('fs');
const path = require('path');
const test = require('node:test');
const assert = require('node:assert/strict');

const root = path.join(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'public', 'admin', 'review.html'), 'utf8');
const js = fs.readFileSync(path.join(root, 'public', 'admin', 'review.js'), 'utf8');
const refresh = fs.readFileSync(path.join(root, 'public', 'admin', 'inbox-refresh.js'), 'utf8');

const htmlBits = [
  'id="product-name"',
  'id="app-version"',
  'id="actor-name"',
  'id="users-link"',
  'href="/admin/audit"',
  'href="/admin/users"',
  'href="/admin/roster"',
  'Nhật ký',
  'Người dùng',
  'Ca trực',
  'Đăng xuất',
  'id="storage"',
  'id="health-banner"',
  'id="updated-at"',
  'id="new-indicator"',
  'id="refresh-now"',
  'id="sync-missed"',
  'Đồng bộ tin bị sót',
  'Làm mới',
  'id="channel-settings-toggle"',
  'Cài đặt kênh',
  'id="channel-panel"',
  'id="channels"',
  'id="add-channel"',
  'id="group-tabs"',
  'data-nhom="zalo"',
  'data-nhom="fb-sale"',
  'data-nhom="fb-dv"',
  'Zalo OA',
  'FB-Sale',
  'FB-DV',
  'id="hot-chip"',
  'id="filter-toggle"',
  'id="filter-panel"',
  'data-triage="hot"',
  'data-triage="urgent"',
  'data-triage="normal"',
  'id="types"',
  'data-type="follower"',
  'data-type="zns"',
  'data-type="broadcast"',
  'id="legacy-ops"',
  'data-ops="sending"',
  'data-ops="queued"',
  'data-ops="failure"',
  'id="zalo-line"',
  'data-zline="sale"',
  'data-zline="dv"',
  'id="folder-nav"',
  'data-folder="pending"',
  'data-folder="sent"',
  'data-folder="bought"',
  'data-folder="hesitant"',
  'data-folder="declined"',
  'data-folder="deleted"',
  'Chờ xử lý',
  'Đã gửi',
  'Đã mua',
  'Do dự',
  'Từ chối',
  'Đã xóa',
  'id="active-filters"',
  'id="list"',
  'id="detail"',
  'id="queue"',
  'id="stats-day"',
  'id="stats-template"',
  'id="create-form"',
  'Thống kê',
  'Tạo tin',
  'Đưa vào chờ xử lý',
  'id="toast"',
  'id="undo-toasts"',
  'inbox-refresh.js',
  'inbox-order.js',
  'kiot-picker.js',
];

const jsBits = [
  "body.appendChild(customerPanel(d))",
  'Hồ sơ khách',
  "text: 'Gắn'",
  "text: 'bỏ'",
  '/admin/api/customers/link',
  '/admin/api/customers/unlink',
  "/customer'",
  'Cho AI học từ câu trả lời này',
  'learn-check',
  "text: 'Duyệt & Gửi'",
  "id = 'btn-approve'",
  'class: \'card-reply\'',
  'class: \'card-actions\'',
  'data-draft-id',
  'class: \'msg-names\'',
  'class: \'name-row\'',
  'class: \'msg-time\'',
  'class: \'msg-sent\'',
  'class: \'reply-error\'',
  "text: 'Xóa'",
  "label: 'Hoàn tác'",
  '/delete',
  '/restore',
  "text: 'Tạo đơn KiotViet'",
  'Xác nhận tạo hoá đơn',
  'Xác nhận tạo đơn đặt hàng',
  "text: 'Kiểm kho và xem lại'",
  "text: 'Điền vào đơn'",
  "text: 'Thêm dòng'",
  '/admin/api/kiotviet/products',
  '/admin/api/kiotviet/quick-entry',
  '/admin/api/kiotviet/customer',
  '/kiotviet',
  'Do dự',
  "'Từ chối'",
  'Đã mua',
  'Trả về Chờ xử lý',
  'Chuyển qua Sale',
  'Chuyển qua DV',
  'Gắn Sale',
  'Gắn DV',
  'class: \'detail-quick\'',
  'statusActions(d)',
  'lineActions(d',
  'Lưu',
  'Từ chối bản nháp',
  'Đưa về chờ xử lý',
  '/admin/api/drafts',
  '/admin/api/channels',
  '/admin/api/stats',
  '/admin/api/inbox/sync',
  '/admin/api/health',
  '/admin/api/session',
  '/folder',
  '/biz-line',
  'me.canSend',
  'me.canDelete',
  'me.canKiot',
  'me.canManageUsers',
  'setInterval',
  'Xóa lọc',
  'Xem tin chờ xử lý',
  'Không tải được hộp thư',
  'Gợi ý: Từ chối',
  'Khách chưa có tên',
  "text: 'Thử lại'",
];

test('inbox keeps every pre-redesign control and API trigger', () => {
  const blob = html + '\n' + js;
  for (const bit of htmlBits) assert.match(html, new RegExp(bit.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  for (const bit of jsBits) assert.match(js, new RegExp(bit.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
  assert.match(blob, /button\.linkish|class: 'linkish'|className = 'linkish'/);
  const keydown = js.slice(js.indexOf("document.addEventListener('keydown'"));
  assert.match(keydown, /ev\.key === 'j'/);
  assert.match(keydown, /ev\.key === 'Escape'/);
  assert.doesNotMatch(keydown.slice(0, 1200), /\bsend\(|\bapprove\(/);
  assert.match(refresh, /Có /);
  assert.match(refresh, /tin mới/);
});
